# Generated by Django 3.0.7 on 2020-06-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcreation',
            name='img_group',
            field=models.ImageField(default='default.jpg', upload_to='group_pics'),
        ),
    ]
